GET http://localhost:3000/account/2/admin/all
x-jwt-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBY2NvdW50RW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwiQWNjb3VudFJvbGUiOiJ1c2VyIiwiRXhwaXJlc0F0IjoxNjgxMzg5NTczfQ.Vkwdp2qH29NoQjgbiOGvBcN0sDyVVrt03Xb1t4PaSe8

###
GET http://localhost:3000/account/1
x-jwt-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBY2NvdW50RW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsIkFjY291bnRSb2xlIjoiYWRtaW4iLCJFeHBpcmVzQXQiOjE2ODEzODUxMzd9.ULwMFJ_wIb5O2QH0exxo7LJPeHk09c8RdoqGIh8SqWY

###
DELETE http://localhost:3000/account/1
x-jwt-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBY2NvdW50RW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwiRXhwaXJlc0F0IjoxNjgxMzgxNDgzfQ.FkMwro0v5iMmG30n4fXIwyWtjd6A8efXMQrLqrs1t5g

###
POST http://localhost:3000/account
content-type: application/json

{
    "name": "test",
    "email": "test@example.com",
    "password": "password"
}

###
POST http://localhost:3000/login
content-type: application/json

{
    "email": "test@example.com",
    "password": "password"
}

###

GET http://localhost:3000/refreshToken
x-refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBY2NvdW50RW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsIkV4cGlyZXNBdCI6MTY4MTQ3MTQ2OH0.H8i2tamNTjpZyBbPVZF6iR7VMyYKH7-OCIv1aGHArfA

###
POST http://localhost:3000/login
content-type: application/json

{
    "email": "admin@example.com",
    "password": "administrator"
}