bind_addr = ":3000"

log_level = "debug"

database_url = "host=localhost port=5432 user=postgres password=iaas dbname=iaas sslmode=disable"

jwt_key = "&E)H@McQfTjWnZr4u7x!A%D*G-JaNdRgUkXp2s5v8y/B?E(H+MbPeShVmYq3t6w9z$C&F)J@NcRfTjWnZr4u7x!A%D*G-KaPdSgVkXp2s5v8y/B?E(H+MbQeThWmZq3t"

[api_admin]
name = "admin"
email = "admin@example.com"
password = "administrator"

[[clusters]]
location = "America/Los_Angeles"
url = "http://192.168.122.20:5000"

[clusters.cluster_admin]
name = "admin"
email = "admin@example.com"
password = "openstack"

[[clusters]]
location = "Europe/Paris"
url = "http://192.168.122.21:5000"

[clusters.cluster_admin]
name = "admin"
email = "admin@example.com"
password = "openstack"

[[clusters]]
location = "Asia/Hong_Kong"
url = "http://192.168.122.22:5000"

[clusters.cluster_admin]
name = "admin"
email = "admin@example.com"
password = "openstack"